### ISSUE TITLE
Realistically running this for low cost?

### ISSUE THREAD

**Issue by chammaaomar** [fundpurifier/app#10]
Salam Alaykum,
Thank you for open-sourcing this! You mention in the README that it costs about $20k / year to run the app. Is there a set of alternative sources that can be queried for financial / halal data cheaply or even freely to get the functionality? even if it's less accurate or able to query the data less often, like on a weekly or monthly basis. This way it's more valuable, not just as a codebase, but an app that can be realistically run. Thanks again!

**Comment by yazinsai** [comment]
Well, well .. what do you know! I just had a look and came across [a new API](https://finnworlds.com/documentation/#ETF_Holdings_API) that providers access to fund holdings (both ETFs & Mutual Funds) for just $19/mo!

**Comment by yazinsai** [comment]
Moved this discussion over to #11
