### ISSUE TITLE
Shariah-compliance checking frequency

### ISSUE THREAD

**Issue by hialradhi** [fundpurifier/app#2]
The system should check Musaffa database for shariah-compliance status regularly, and update the stock status in each portfolio. If a stock turns non-compliant, should be reflected in the funds list status, and notify the user based on the specified settings.

Currently, I checked Musaffa manually for each stock in a fund, and there are multiple stocks that turned non-compliant, but that did not reflect in the stocks status. 
- it could be an issue with retrieving shariah-compliance status from Musaffa
- other possibility is that the system does not check as frequent as it should, running behind the latest updates from Musaffa 

Example: 
$GOOS status in Musaffa is Not Halal (non-compliant), but the system is still showing it as compliant stock. 

<img width="488" alt="‏لقطة الشاشة 2023-11-14 في 5 15 54 م" src="https://github.com/fundpurifier/app/assets/150816070/79a8bcd8-d3b3-4f00-9ee2-70df8fb11bdc">
<img width="472" alt="‏لقطة الشاشة 2023-11-14 في 5 15 35 م" src="https://github.com/fundpurifier/app/assets/150816070/2a804d20-2d35-468a-b9a4-beb7a7c967f3">

**Comment by yazinsai** [comment]
Thanks for flagging this issue. We refresh the Shariah status on the 15th and 28th of each month: https://github.com/fundpurifier/app/blob/6f84d05ec9915e2e6415eb8173592f29e6355833/src/workers/scheduler.ts#L31 

This check ran at midnight, and you should've already received an email notification of the 24 hour sell notice. (Let me know if not)

I can see that `GOOS` is indeed shown as non-compliant now:

![image](https://github.com/fundpurifier/app/assets/1846034/329f1857-5530-4028-b094-a2dd30faadfb)

There's no reason why we can't make these checks more frequently, besides possibly the nuisance of having multiple "asset turned non-compliant" emails. Weekly perhaps?

**Comment by hialradhi** [comment]
Thanks for the reply, Yazin. 

I received the email notification of sell notice, but it included (in addition to GOOS and other) a few stocks that I don’t any shares of them, which is weird.

see the attached Screenshot:
![IMG_8203](https://github.com/fundpurifier/app/assets/150816070/82ec6bed-750c-4d77-8a7b-8180e4116fbc)

**Comment by yazinsai** [comment]
Thanks @hialradhi, just pushed a fix to exclude empty positions from the email notification
