### ISSUE TITLE
Development instructions clarification

### ISSUE THREAD

**Issue by zeekojaegar** [fundpurifier/app#7]
A couple of things in the README.md and actual code are conflicting and it's a little hard to get this up and running locally.

### The envs

Almost all of the envs are behind a `requireEnv` function ([example](https://github.com/fundpurifier/app/blob/bc9dc80ddbd2a6a806757c182f0ecc8e77b47e1d/src/lib/fmp/index.ts#L12)).

There are in the README, but the `.env.example` says that the ALPACA apis are only required for production
```
ALPACA_CLIENT_ID=
ALPACA_CLIENT_SECRET=
CLERK_SECRET_KEY=
RESEND_KEY=
```

After obtaining the alpaca APIs, the sign in requires you to go to the official `Alpaca` registration. Should I update the routes to reflect the sandboxes shown in their documentation for development? Or should the mocks take care of this?

### Mocks

The Mocks don't seem to run initially but I'm assuming these run after the initial load passed the login.

Thank you for all you do!

**Comment by yazinsai** [comment]
Resolved in #8, thank you for the issue @zeekojaegar
